version: '3.1'

services:
  mysql:
    image: mysql
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: escolaist
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/mysql:/var/lib/mysql

  phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8082:80
      environment:
        - PMA_ARBITRARY=1
        - UPLOAD_LIMIT=30M

  php-7.4:
    image: arodax/php7.4-apache:latest
    container_name: phpIst
    ports:
      - 8080:80
    volumes:
      - ./log/apache2:/var/log/apache2
      - ./html:/var/www/html
      
    depends_on:
      - mysql
      - phpmyadmin